---

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Add nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/cats.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Symlink nginx conf to activate 
  file:
    src: /etc/nginx/sites-available/cats.conf
    dest: /etc/nginx/sites-enabled/cats.conf
    state: link



