---
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
ssh_public_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
ssh_public_key: "{{ lookup('file', ssh_public_key_file) }}"
machine_security_groups:
  - {group: "bastion{{ suffix }}", port: 22, remote_ip_prefix: "202.78.240.7/32"}
  - {group: "bastion{{ suffix }}", port: 22, remote_ip_prefix: "{{ ssh_remote_cidr }}"}
security_groups: "{{ machine_security_groups }}"
