---

machine_security_groups:
  - {group: "web{{ suffix }}", port: 80, remote_group: "lb{{ suffix }}"}
  - {group: "web{{ suffix }}", port: 443, remote_group: "lb{{ suffix }}"}
security_groups: "{{ machine_security_groups + main_security_groups }}"

