---
- name: Set up python application
  hosts: localhost
  vars_files:
    - secrets.yml
  vars:
    database_user: admin
    database: cat_pics
    database_host: localhost
  environment:
    PGPASSWORD: "{{ vault_database_password }}"
  tasks:

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes

    - name: Install needed libraries
      become: yes
      apt:
        name: "{{ item }}"  
        state: present
      with_items:
        - python3-dev
        - python3-psycopg2
        - python-psycopg2
        - postgresql

    - name: Check out code for project
      debug:
        msg: Check out code for project

    - name: Create python virtual environment
      debug:
        msg: Create python virtual environment

    - name: Add app config
      debug:
        msg: Adding application config

    - name: Create DB user
      debug:
        msg: Create DB user

    - name: Make postgres listen on external ports
      debug: 
        msg: Make db listen on certain ports
      notify: restart postgres

    - name: Create the database
      debug:
        msg: Create the database

    - name: Create table for pics 
      debug:
        msg: Creating the db table

    - name: Add images to new table
      debug:
        msg: Add images to the db
      

  handlers:
    - name: restart postgres
      debug:
        msg: Restarted postgres

