
- name: Update apt cache
  raw: apt update -y

- name: Install python
  raw: >
    which python || apt-get install -y python && echo 'installed'
  register: python
  changed_when: python.stdout == 'installed'

- name: Add NZ locale to all instances
  locale_gen:
    name: en_NZ.UTF-8
    state: present

- name: Add entry to /etc/hosts for all instances
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].private_v4 | default(hostvars[item].ansible_default_ipv4.address) }} {{ item }}"
  with_items: "{{ host_set }}"
