---
- name: Set up python application
  hosts: localhost
  tasks:

    - name: Update apt cache
      with_items:
        - python3-dev
        - python3-psycopg2
        - python-psycopg2
        - postgresql
      debug:
        msg: Installing  "{{ item }}"

    - name: Check out code for project
      debug:
        msg: Checking out code for our project

    - name: Create python virtual environment
      debug:
        msg: Creating python virtual environment

    - name: Add app config
      debug:
        msg: Adding application config

    - name: Create DB user
      debug:
        msg: Create DB user

    - name: Make postgres listen on external ports
      debug: 
        msg: Make db listen on certain ports
      notify: restart postgres

    - name: Create the database
      debug:
        msg: Create the database

    - name: Create table for pics 
      debug:
        msg: Creating the db table

    - name: Add images to new table
      debug:
        msg: Add images to the db
      
  handlers:
    - name: restart postgres
      debug:
        msg: Restarted postgres

  
