---

- name: Add dynamic hosts to inventory
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Add loadbalancer to inventory
      add_host:
        name: "{{ prefix }}-lb-{{ app_version }}"
        groups: mycluster,loadbalancer,mycluster_new,loadbalancer_new

    - name: Add web hosts to inventory
      add_host:
        name: "{{ prefix }}-web-{{ app_version }}-{{ item }}"
        groups: mycluster,web,mycluster_new
      with_sequence: count=2

    - name: Add app hosts to inventory
      add_host:
        name: "{{ prefix }}-app-{{ app_version }}-{{ item }}"
        groups: mycluster,app,mycluster_new
      with_sequence: count=2

