---
- name: Add new hosts to inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - fail:
      when: suffix is not defined or suffix == ""

    - fail:
      when: suffix is not defined or suffix == ""

    - fail:
      when: prefix is not defined or prefix == ""

    - name: Add new web host to inventory
      add_host:
        name: "{{ prefix }}-web-{{ version }}"
        groups: mycluster,web,web-new


    - name: Add new app host to inventory
      add_host:
        name: "{{ prefix }}-app-{{ version }}"
        groups: mycluster,app,app-new


- name: Preflight to set up machine specific variables
  hosts: "mycluster"
  gather_facts: false
  tasks:


- name: Provision a set of hosts in the Catalyst Cloud
  hosts: localhost
  gather_facts: false
  vars:
    # optional suffix to namespace resources
    suffix: ""
    host_set: "{{ groups['mycluster'] | unique | list }}"
    # change if required or override at runtime using --extra-vars

    security_groups: "{{ host_set | map('extract', hostvars, 'security_groups') | sum(start=[]) | unique | list }}"

    security_group_names: "{{ security_groups | map(attribute='group') | unique | list }}"

  tasks:
    
    - debug:
        var:  groups.mycluster

    - debug:
        var:  groups.web
