---

- name: Playbook with a lot of tasks
  hosts: localhost
  become: true
  vars:
    database_user: train
    database_password: mypassword
  tasks:

    - debug:
        msg: Running some basic setup tasks

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install monitoring packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - htop
        - monit


    - debug:
        msg: Set up database

    - name: Install database
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql

    - name: Make postgres listen on external ports
      lineinfile:
        path: /etc/postgresql/9.5/main/postgresql.conf
        line: "listen_addresses = '*'"
        insertbefore: '^#listen_addresses'
      notify: restart postgres

    - name: Add pb_hba rule for hosts
      lineinfile:
        path: /etc/postgresql/9.5/main/pg_hba.conf
        insertafter: "^# IPv4 local connections"
        line: "host      all    all   192.168.99.0/24     md5"
      notify: restart postgres

    - name: Create DB user
      become: true
      become_user: postgres
      postgresql_user:
        name: "{{ database_user }}"
        password: "{{ database_password }}"


    - name: Create the database
      become: true
      become_user: postgres
      postgresql_db:
        name: "{{ database }}"
        owner: "{{ database_user }}"
        encoding: UTF8
        lc_ctype: en_NZ.UTF-8
        lc_collate: en_NZ.UTF-8
        template: template0



    - name: Set up local virtual environment
      pip:
        virtualenv_python: python3
        virtualenv: venv
        chdir: ..
        name: "{{ item }}"
      with_items:
        - Flask
        - psycopg2


      
