---
- name: Set up python application
  hosts: localhost
  vars_files:
    - secrets.yml
  vars:
    database_user: admin
    database: cat_pics
    database_host: localhost
  tasks:

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes

    - name: Install needed libraries
      become: yes
      apt:
        name: "{{ item }}"  
        state: present
      with_items:
        - python3-dev
        - python3-psycopg2
        - python-psycopg2
        - postgresql

    - name: Check out code for project
      git:
        repo: https://github.com/heytrav/sample-flask-app.git
        dest: "{{ ansible_env.HOME }}/sample-flask-app"

    - name: Create python virtual environment
      pip:
        virtualenv_python: python3
        chdir: "{{ ansible_env.HOME }}/sample-flask-app"
        virtualenv: "{{ ansible_env.HOME }}/sample-flask-app/venv"
        requirements: requirements.txt

    - name: Add app config
      template:
        src: templates/config.py.j2
        dest: "{{ ansible_env.HOME }}/sample-flask-app/config.py"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0644

    - name: Create DB user
      become: true
      become_user: postgres
      postgresql_user:
        name: "{{ database_user }}"
        password: "{{ vault_database_password }}"


    - name: Create the database
      become: true
      become_user: postgres
      postgresql_db:
        name: "{{ database }}"
        owner: "{{ database_user }}"
        encoding: UTF8
        lc_ctype: en_NZ.UTF-8
        lc_collate: en_NZ.UTF-8
        template: template0

