---
- name: Preflight to add hosts to inventory
  hosts: localhost
  gather_facts: false
  vars:
    suffix: "{{ app_suffix | mandatory }}"
    prefix: "{{ app_prefix | mandatory }}"
    version: "{{ app_version | mandatory }}"
  tasks:

    - name: Add loadbalancer to inventory
      add_host:
        name: "{{ prefix }}-lb-{{ app_version }}"
        groups: mycluster,loadbalancer,mycluster_new

    - name: Add web hosts to inventory
      add_host:
        name: "{{ prefix }}-web-{{ app_version }}-{{ item }}"
        groups: mycluster,web,mycluster_new
      with_sequence: count=2

    - name: Add app hosts to inventory
      add_host:
        name: "{{ prefix }}-app-{{ app_version }}-{{ item }}"
        groups: mycluster,app,mycluster_new
      with_sequence: count=2



- name: Provision a set of hosts in the Catalyst Cloud
  hosts: localhost
  gather_facts: false
  vars:
    host_set: "{{ groups.mycluster | unique | list }}"
    public_hosts: "{{ groups.loadbalancer | union(groups.bastion) | unique | list }}"
    security_groups: "{{ host_set | map('extract', hostvars, 'security_groups') | sum(start=[]) | unique | list }}"

    security_group_names: "{{ security_groups | map(attribute='group') | unique | list }}"

  roles:
    - role: os-provision

  post_tasks:

    - name: Remove ip from known hosts
      known_hosts:
        name: "{{ item }}"
        state: absent
      with_items: "{{ host_set }}"

    - name: Set ansible_host for bastion to be public ip
      add_host:
        name: "{{ item }}"
        ansible_host: "{{ hostvars[item].floating_ip }}"
      with_items: "{{ groups.bastion }}"

    - include_tasks: tasks/update-ssh-config.yml
      vars:
        ip: "{{ hostvars[item].private_v4 }}"
      with_items: "{{ groups.mycluster | difference(groups.bastion) }}"

    - include_tasks: tasks/update-ssh-config.yml
      vars:
        ip: "{{ hostvars[item].ansible_host }}"
      with_items: "{{ groups.bastion }}"


    - wait_for:
        host: "{{ item }}"
        port: 22
      with_items: "{{ groups.bastion }}"


- name: Basic host setup
  hosts: bastion
  become: true
  gather_facts: false
  vars:
    host_set: "{{ groups.mycluster }}"
  roles:
    - role: common

- name: Basic host setup
  hosts: mycluster:!bastion
  become: true
  gather_facts: false
  vars:
    host_set: "{{ groups.mycluster }}"
  roles:
    - role: common


- name: Extra set up for web demo
  hosts: "loadbalancer"
  become: true
  gather_facts: false
  tasks:

    - name: "Add fake domain to /etc/hosts"
      delegate_to: localhost
      become: yes
      blockinfile:
        dest: /etc/hosts
        insertafter: EOF
        block: |
          {{ floating_ip }} my-app.cat
        marker: "# {mark} ANSIBLE MANAGED BLOCK for my-app.cat"

