---
- name: Explore set functions in groups
  hosts: mycluster
  gather_facts: false
  tasks:

    - name: Output server type
      debug:
        var: inventory_hostname

- name: Union of hosts
  hosts: web:db
  gather_facts: false
  tasks:

    - name: Output union of web and db
      debug:
        var: inventory_hostname

- name: Intersection of hosts
  hosts: web:&blue
  gather_facts: false
  tasks:
    - name: Output intersection of web and blue
      debug:
        var: inventory_hostname


- name: Intersection of hosts
  hosts: app:&green
  gather_facts: false
  tasks:
    - name: Output intersection of app and green
      debug:
        var: inventory_hostname



- name: Difference of groups
  hosts: wellington:!blue
  gather_facts: false
  tasks:
    - name: Output difference of blue and green
      debug:
        var: inventory_hostname

