- name: Run a set of tools in local directory
  hosts: localhost
  tasks:

    - name: Delete a branch from repository
      command: git branch -D notabranch


    - name: Run tools command in working directory
      shell: "{{ ansible_env.PWD }}/tools.sh"

  


      
         
