ssh_user: train
ssh_public_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
ssh_public_key: "{{ lookup('file', ssh_public_key_file) }}"
#ssh_public_key: |
  #ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDhElkUjFH0fBKQ2Voifqp2dPRjH/Ski7SXj4uQlZWnyPhILWV/rErcVElMWpokhB4MmGZBgsJUvBSMBcb2HnWUyKszdO0sah0OHTDNRpEP1NbtNdJMWuJsTz2Z3VOMBVisU8TsKXPv6TKj/PYE21W7/A0LhY16pi+NNB7WrKRDCo2jy18c1fDw3l7+Xtb87TDBpR3CjIez9RfUYQbauQ1ZHdR43jeHinkpAKqmlMK8H7a0aKjM1QuH8BvtKhLTh2StjOYkI5srbk8+EC3N7e7iN6OL3i0UQGa4q486xcDVSJi+tBCrA9V3oDHGnVJ/TFF4H+maoiKAI7xF9a9woko/ Setup for bastion access
keypair_name: "training-key{{ suffix }}"
ssh_remote_cidr: "{{ lookup('dig', 'myip.opendns.com', '@resolver1.opendns.com') + '/32' | default('0.0.0.0/0', true) }}"
network_name: "training-net{{ suffix }}"
public_net_name: public-net
subnet_name: "training-subnet{{ suffix }}"
router_name: "training-router{{ suffix }}"
subnet_prefix: 192.168.99
subnet_cidr: "{{ subnet_prefix }}.0/24"
subnet_dhcp_start: "{{ subnet_prefix }}.98"
subnet_dhcp_end: "{{ subnet_prefix }}.200"

default_os_image: ubuntu-16.04-x86_64
default_flavor: c1.c1r1

region_nameservers:
  nz-por-1: [202.78.247.197, 202.78.247.198, 202.78.247.199]
  nz_wlg_2: [202.78.240.213, 202.78.240.214, 202.78.240.215]
  nz-hlz-1: [202.78.244.85, 202.78.244.86, 202.78.244.87]

default_nameservers: "{{ region_nameservers[lookup('env', 'OS_REGION_NAME')] }}"

main_security_groups:
  - {group: "managed{{ suffix }}", port: 22, remote_group: "bastion{{ suffix }}"}
database_user: train_user
database: cat_pics
