---
- name: Upgrade application in place
  become: true
  hosts: app
  serial: 1
  any_errors_fatal: true
  vars:
    web_server: "{{ inventory_hostname | regex_replace('^(.*)app(\\d+)$', '\\1web\\2') }}"
  tags:
    - app
  tasks:

    - name: Stop the gunicorn service
      systemd:
        name: gunicorn
        state: stopped

    - name: Disable application at load balancer
      haproxy:
        backend: catapp-backend
        host: "{{ web_server }}"
        state: disabled
      delegate_to: "{{ groups.loadbalancer[0] }}"

    - name: Checkout application from git
      git:
        repo: https://github.com/heytrav/sample-flask-app.git
        dest: "{{ app_directory }}"
        version: "{{ app_version | default('master') }}"
      notify: start gunicorn
    
    - name: Add app config
      template:
        src: templates/config.py.j2
        dest: "{{ app_directory }}/config.py"
        owner: train
        group: train
        mode: 0644
      notify: restart gunicorn

    - name: Install app requirements
      pip:
        requirements: "{{ app_directory }}/requirements.txt"
        virtualenv: "{{ app_directory }}/venv"
        virtualenv_python: /usr/bin/python3

    - name: Install gunicorn
      pip:
        name: gunicorn
        virtualenv: "{{ app_directory }}/venv"

    - name: Add systemd config
      template:
        src: templates/gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service
        owner: root
        group: root
        mode: 0644
      notify: restart gunicorn

    - meta: flush_handlers

    - name: Make sure gunicorn is accepting connections
      wait_for:
        port: 5000

    - name: Re-enable application at load balancer
      haproxy:
        backend: catapp-backend
        host: "{{ web_server }}"
        state: enabled
      delegate_to: "{{ groups.loadbalancer[0] }}"


  handlers:
    - name: start gunicorn
      systemd:
        name: gunicorn
        state: started

