- name: Play with some set theory filters
  hosts: localhost
  gather_facts: false
  vars: 
    list1:
      - apple
      - banana
      - orange
      - lime
      - strawberry
    list2:
      - apple
      - strawberry
      - peach
      - pear
      - kiwi
    firstlist: "{{ list1 | union(list2) }}"
    secondlist: "{{ list1 | intersect(list2) }}"
    thirdlist: "{{ list1 | difference(list2) }}"
  tasks:

    - debug:
        var: firstlist

    - debug:
        var: secondlist

    - debug:
        var: thirdlist
